# Site settings
title: thenyel
description: Danniel's Blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thenyel.com" # the base hostname & protocol for your site
twitter_username: nyelcondez
github_username:  ducondez

# Build settings
markdown: kramdown
